import { v4 as uuidv4 } from 'uuid';
import { format, addDays, setHours, setMinutes, setSeconds } from 'date-fns';
import type { Kysely } from 'kysely';
import type { Database } from '@/lib/database/types';

export const MOCK_DATA_MARKER = 'mock-data';

function isoNow(): string {
  return format(new Date(), "yyyy-MM-dd'T'HH:mm:ss");
}

function isoDate(date: Date): string {
  return format(date, "yyyy-MM-dd'T'HH:mm:ss");
}

function appointmentTime(daysFromNow: number, hour: number, minute = 0): Date {
  const d = addDays(new Date(), daysFromNow);
  return setSeconds(setMinutes(setHours(d, hour), minute), 0);
}

export async function seedMockData(db: Kysely<Database>, userId: string): Promise<void> {
  // Clean existing data first to make seeding idempotent
  await cleanupMockData(db, userId);

  const now = isoNow();

  // ── Services ────────────────────────────────────────────────────────────────
  const serviceIds = {
    fullGroom: uuidv4(),
    bathBrush: uuidv4(),
    nailTrim: uuidv4(),
    puppyFirstGroom: uuidv4(),
    deshedding: uuidv4(),
  };

  await db.insertInto('services').values([
    {
      id: serviceIds.fullGroom,
      user_id: userId,
      name: 'Full Grooming',
      description: MOCK_DATA_MARKER,
      duration_minutes: 90,
      price_cents: 7500,
      location_type: 'client_location',
      weather_dependent: 0,
      created_at: now,
      updated_at: now,
      version: 1,
      needs_sync: 0,
      sync_operation: null,
      synced_at: null,
      deleted_at: null,
    },
    {
      id: serviceIds.bathBrush,
      user_id: userId,
      name: 'Bath & Brush',
      description: MOCK_DATA_MARKER,
      duration_minutes: 60,
      price_cents: 4500,
      location_type: 'client_location',
      weather_dependent: 0,
      created_at: now,
      updated_at: now,
      version: 1,
      needs_sync: 0,
      sync_operation: null,
      synced_at: null,
      deleted_at: null,
    },
    {
      id: serviceIds.nailTrim,
      user_id: userId,
      name: 'Nail Trim',
      description: MOCK_DATA_MARKER,
      duration_minutes: 30,
      price_cents: 2000,
      location_type: 'mobile',
      weather_dependent: 0,
      created_at: now,
      updated_at: now,
      version: 1,
      needs_sync: 0,
      sync_operation: null,
      synced_at: null,
      deleted_at: null,
    },
    {
      id: serviceIds.puppyFirstGroom,
      user_id: userId,
      name: 'Puppy First Groom',
      description: MOCK_DATA_MARKER,
      duration_minutes: 45,
      price_cents: 3500,
      location_type: 'business_location',
      weather_dependent: 0,
      created_at: now,
      updated_at: now,
      version: 1,
      needs_sync: 0,
      sync_operation: null,
      synced_at: null,
      deleted_at: null,
    },
    {
      id: serviceIds.deshedding,
      user_id: userId,
      name: 'De-shedding Treatment',
      description: MOCK_DATA_MARKER,
      duration_minutes: 75,
      price_cents: 6000,
      location_type: 'client_location',
      weather_dependent: 1,
      created_at: now,
      updated_at: now,
      version: 1,
      needs_sync: 0,
      sync_operation: null,
      synced_at: null,
      deleted_at: null,
    },
  ]).execute();

  // ── Clients ─────────────────────────────────────────────────────────────────
  const clientIds = {
    sarah: uuidv4(),
    mike: uuidv4(),
    emily: uuidv4(),
    james: uuidv4(),
    lisa: uuidv4(),
    david: uuidv4(),
  };

  await db.insertInto('clients').values([
    {
      id: clientIds.sarah,
      user_id: userId,
      first_name: 'Sarah',
      last_name: 'Johnson',
      email: 'sarah@email.com',
      phone: '(512) 555-0101',
      address: '1234 Oak Hill Dr, Austin, TX 78749',
      latitude: 30.2420,
      longitude: -97.8528,
      notes: MOCK_DATA_MARKER,
      scheduling_flexibility: 'unknown' as const,
      created_at: now,
      updated_at: now,
      version: 1,
      needs_sync: 0,
      sync_operation: null,
      synced_at: null,
      deleted_at: null,
    },
    {
      id: clientIds.mike,
      user_id: userId,
      first_name: 'Mike',
      last_name: 'Chen',
      email: 'mike.chen@email.com',
      phone: '(512) 555-0102',
      address: '5678 Bee Cave Rd, Austin, TX 78746',
      latitude: 30.2960,
      longitude: -97.8370,
      notes: MOCK_DATA_MARKER,
      scheduling_flexibility: 'unknown' as const,
      created_at: now,
      updated_at: now,
      version: 1,
      needs_sync: 0,
      sync_operation: null,
      synced_at: null,
      deleted_at: null,
    },
    {
      id: clientIds.emily,
      user_id: userId,
      first_name: 'Emily',
      last_name: 'Rodriguez',
      email: 'emily.r@email.com',
      phone: '(512) 555-0103',
      address: '910 S Lamar Blvd, Austin, TX 78704',
      latitude: 30.2530,
      longitude: -97.7630,
      notes: MOCK_DATA_MARKER,
      scheduling_flexibility: 'unknown' as const,
      created_at: now,
      updated_at: now,
      version: 1,
      needs_sync: 0,
      sync_operation: null,
      synced_at: null,
      deleted_at: null,
    },
    {
      id: clientIds.james,
      user_id: userId,
      first_name: 'James',
      last_name: 'Wilson',
      email: 'james.w@email.com',
      phone: '(512) 555-0104',
      address: '2345 N Mopac Expy, Austin, TX 78731',
      latitude: 30.3590,
      longitude: -97.7480,
      notes: MOCK_DATA_MARKER,
      scheduling_flexibility: 'unknown' as const,
      created_at: now,
      updated_at: now,
      version: 1,
      needs_sync: 0,
      sync_operation: null,
      synced_at: null,
      deleted_at: null,
    },
    {
      id: clientIds.lisa,
      user_id: userId,
      first_name: 'Lisa',
      last_name: 'Park',
      email: 'lisa.park@email.com',
      phone: '(512) 555-0105',
      address: '6789 E Riverside Dr, Austin, TX 78741',
      latitude: 30.2340,
      longitude: -97.7170,
      notes: MOCK_DATA_MARKER,
      scheduling_flexibility: 'unknown' as const,
      created_at: now,
      updated_at: now,
      version: 1,
      needs_sync: 0,
      sync_operation: null,
      synced_at: null,
      deleted_at: null,
    },
    {
      id: clientIds.david,
      user_id: userId,
      first_name: 'David',
      last_name: 'Thompson',
      email: 'david.t@email.com',
      phone: '(512) 555-0106',
      address: '3456 W Anderson Ln, Austin, TX 78757',
      latitude: 30.3580,
      longitude: -97.7370,
      notes: MOCK_DATA_MARKER,
      scheduling_flexibility: 'unknown' as const,
      created_at: now,
      updated_at: now,
      version: 1,
      needs_sync: 0,
      sync_operation: null,
      synced_at: null,
      deleted_at: null,
    },
  ]).execute();

  // ── Pets ─────────────────────────────────────────────────────────────────────
  const petIds = {
    buddy: uuidv4(),
    whiskers: uuidv4(),
    luna: uuidv4(),
    max: uuidv4(),
    coco: uuidv4(),
    rocky: uuidv4(),
    daisy: uuidv4(),
    bear: uuidv4(),
  };

  await db.insertInto('pets').values([
    {
      id: petIds.buddy,
      client_id: clientIds.sarah,
      name: 'Buddy',
      species: 'dog',
      breed: 'Golden Retriever',
      size: 'large',
      age_years: 5,
      weight_lbs: 70,
      behavior_notes: MOCK_DATA_MARKER,
      medical_notes: null,
      created_at: now,
      updated_at: now,
      version: 1,
      needs_sync: 0,
      sync_operation: null,
      synced_at: null,
      deleted_at: null,
    },
    {
      id: petIds.whiskers,
      client_id: clientIds.sarah,
      name: 'Whiskers',
      species: 'cat',
      breed: 'Maine Coon',
      size: 'medium',
      age_years: 3,
      weight_lbs: 15,
      behavior_notes: MOCK_DATA_MARKER,
      medical_notes: null,
      created_at: now,
      updated_at: now,
      version: 1,
      needs_sync: 0,
      sync_operation: null,
      synced_at: null,
      deleted_at: null,
    },
    {
      id: petIds.luna,
      client_id: clientIds.mike,
      name: 'Luna',
      species: 'dog',
      breed: 'French Bulldog',
      size: 'small',
      age_years: 2,
      weight_lbs: 25,
      behavior_notes: MOCK_DATA_MARKER,
      medical_notes: null,
      created_at: now,
      updated_at: now,
      version: 1,
      needs_sync: 0,
      sync_operation: null,
      synced_at: null,
      deleted_at: null,
    },
    {
      id: petIds.max,
      client_id: clientIds.emily,
      name: 'Max',
      species: 'dog',
      breed: 'German Shepherd',
      size: 'large',
      age_years: 4,
      weight_lbs: 85,
      behavior_notes: MOCK_DATA_MARKER,
      medical_notes: null,
      created_at: now,
      updated_at: now,
      version: 1,
      needs_sync: 0,
      sync_operation: null,
      synced_at: null,
      deleted_at: null,
    },
    {
      id: petIds.coco,
      client_id: clientIds.emily,
      name: 'Coco',
      species: 'dog',
      breed: 'Poodle',
      size: 'medium',
      age_years: 6,
      weight_lbs: 45,
      behavior_notes: MOCK_DATA_MARKER,
      medical_notes: null,
      created_at: now,
      updated_at: now,
      version: 1,
      needs_sync: 0,
      sync_operation: null,
      synced_at: null,
      deleted_at: null,
    },
    {
      id: petIds.rocky,
      client_id: clientIds.james,
      name: 'Rocky',
      species: 'dog',
      breed: 'Labrador',
      size: 'large',
      age_years: 3,
      weight_lbs: 75,
      behavior_notes: MOCK_DATA_MARKER,
      medical_notes: null,
      created_at: now,
      updated_at: now,
      version: 1,
      needs_sync: 0,
      sync_operation: null,
      synced_at: null,
      deleted_at: null,
    },
    {
      id: petIds.daisy,
      client_id: clientIds.lisa,
      name: 'Daisy',
      species: 'dog',
      breed: 'Yorkshire Terrier',
      size: 'tiny',
      age_years: 7,
      weight_lbs: 6,
      behavior_notes: MOCK_DATA_MARKER,
      medical_notes: null,
      created_at: now,
      updated_at: now,
      version: 1,
      needs_sync: 0,
      sync_operation: null,
      synced_at: null,
      deleted_at: null,
    },
    {
      id: petIds.bear,
      client_id: clientIds.david,
      name: 'Bear',
      species: 'dog',
      breed: 'Bernese Mountain Dog',
      size: 'giant',
      age_years: 2,
      weight_lbs: 100,
      behavior_notes: MOCK_DATA_MARKER,
      medical_notes: null,
      created_at: now,
      updated_at: now,
      version: 1,
      needs_sync: 0,
      sync_operation: null,
      synced_at: null,
      deleted_at: null,
    },
  ]).execute();

  // ── Appointments ─────────────────────────────────────────────────────────────
  const appts = [
    {
      // Day 0 - 9am - completed
      clientId: clientIds.sarah,
      petId: petIds.buddy,
      serviceId: serviceIds.fullGroom,
      start: appointmentTime(0, 9, 0),
      durationMinutes: 90,
      status: 'completed' as const,
      address: '1234 Oak Hill Dr, Austin, TX 78749',
    },
    {
      // Day 0 - 11am - completed
      clientId: clientIds.emily,
      petId: petIds.coco,
      serviceId: serviceIds.bathBrush,
      start: appointmentTime(0, 11, 0),
      durationMinutes: 60,
      status: 'completed' as const,
      address: '910 S Lamar Blvd, Austin, TX 78704',
    },
    {
      // Day 1 - 9am - confirmed
      clientId: clientIds.mike,
      petId: petIds.luna,
      serviceId: serviceIds.puppyFirstGroom,
      start: appointmentTime(1, 9, 0),
      durationMinutes: 45,
      status: 'confirmed' as const,
      address: '5678 Bee Cave Rd, Austin, TX 78746',
    },
    {
      // Day 1 - 2pm - confirmed
      clientId: clientIds.james,
      petId: petIds.rocky,
      serviceId: serviceIds.nailTrim,
      start: appointmentTime(1, 14, 0),
      durationMinutes: 30,
      status: 'confirmed' as const,
      address: '2345 N Mopac Expy, Austin, TX 78731',
    },
    {
      // Day 2 - 10am - scheduled
      clientId: clientIds.emily,
      petId: petIds.max,
      serviceId: serviceIds.deshedding,
      start: appointmentTime(2, 10, 0),
      durationMinutes: 75,
      status: 'scheduled' as const,
      address: '910 S Lamar Blvd, Austin, TX 78704',
    },
    {
      // Day 3 - 9am - scheduled
      clientId: clientIds.david,
      petId: petIds.bear,
      serviceId: serviceIds.fullGroom,
      start: appointmentTime(3, 9, 0),
      durationMinutes: 90,
      status: 'scheduled' as const,
      address: '3456 W Anderson Ln, Austin, TX 78757',
    },
    {
      // Day 5 - 1pm - scheduled
      clientId: clientIds.lisa,
      petId: petIds.daisy,
      serviceId: serviceIds.bathBrush,
      start: appointmentTime(5, 13, 0),
      durationMinutes: 60,
      status: 'scheduled' as const,
      address: '6789 E Riverside Dr, Austin, TX 78741',
    },
    {
      // Day 7 - 10am - scheduled
      clientId: clientIds.sarah,
      petId: petIds.whiskers,
      serviceId: serviceIds.nailTrim,
      start: appointmentTime(7, 10, 0),
      durationMinutes: 30,
      status: 'scheduled' as const,
      address: '1234 Oak Hill Dr, Austin, TX 78749',
    },
  ];

  await db.insertInto('appointments').values(
    appts.map((a) => {
      const end = new Date(a.start.getTime() + a.durationMinutes * 60 * 1000);
      return {
        id: uuidv4(),
        user_id: userId,
        client_id: a.clientId,
        pet_id: a.petId,
        service_id: a.serviceId,
        start_time: isoDate(a.start),
        end_time: isoDate(end),
        status: a.status,
        location_type: 'client_location',
        address: a.address,
        latitude: null,
        longitude: null,
        notes: null,
        internal_notes: MOCK_DATA_MARKER,
        weather_alert: 0,
        created_at: now,
        updated_at: now,
        version: 1,
        needs_sync: 0,
        sync_operation: null,
        synced_at: null,
        deleted_at: null,
      };
    })
  ).execute();
}

export async function cleanupMockData(db: Kysely<Database>, userId: string): Promise<void> {
  await db.deleteFrom('appointments').where('user_id', '=', userId).execute();
  await db.deleteFrom('pets')
    .where('client_id', 'in',
      db.selectFrom('clients').select('id').where('user_id', '=', userId)
    )
    .execute();
  await db.deleteFrom('clients').where('user_id', '=', userId).execute();
  await db.deleteFrom('services').where('user_id', '=', userId).execute();
}
