/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardWeatherRouteImport } from './routes/dashboard/weather'
import { Route as DashboardServicesRouteImport } from './routes/dashboard/services'
import { Route as DashboardRoutesRouteImport } from './routes/dashboard/routes'
import { Route as DashboardChatRouteImport } from './routes/dashboard/chat'
import { Route as DashboardAppointmentsRouteImport } from './routes/dashboard/appointments'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardClientsIndexRouteImport } from './routes/dashboard/clients/index'
import { Route as BookTokenIndexRouteImport } from './routes/book/$token/index'
import { Route as DashboardSettingsProfileRouteImport } from './routes/dashboard/settings/profile'
import { Route as DashboardSettingsMessagingRouteImport } from './routes/dashboard/settings/messaging'
import { Route as DashboardSettingsBillingRouteImport } from './routes/dashboard/settings/billing'
import { Route as DashboardClientsIdRouteImport } from './routes/dashboard/clients/$id'
import { Route as BookTokenConfirmedRouteImport } from './routes/book/$token/confirmed'

const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWeatherRoute = DashboardWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServicesRoute = DashboardServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRoutesRoute = DashboardRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatRoute = DashboardChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppointmentsRoute = DashboardAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsIndexRoute = DashboardClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => DashboardRoute,
} as any)
const BookTokenIndexRoute = BookTokenIndexRouteImport.update({
  id: '/book/$token/',
  path: '/book/$token/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsProfileRoute =
  DashboardSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsMessagingRoute =
  DashboardSettingsMessagingRouteImport.update({
    id: '/settings/messaging',
    path: '/settings/messaging',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsBillingRoute =
  DashboardSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardClientsIdRoute = DashboardClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const BookTokenConfirmedRoute = BookTokenConfirmedRouteImport.update({
  id: '/book/$token/confirmed',
  path: '/book/$token/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/offline': typeof OfflineRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/routes': typeof DashboardRoutesRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/weather': typeof DashboardWeatherRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/book/$token/confirmed': typeof BookTokenConfirmedRoute
  '/dashboard/clients/$id': typeof DashboardClientsIdRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/messaging': typeof DashboardSettingsMessagingRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/book/$token/': typeof BookTokenIndexRoute
  '/dashboard/clients/': typeof DashboardClientsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/offline': typeof OfflineRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/routes': typeof DashboardRoutesRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/weather': typeof DashboardWeatherRoute
  '/dashboard': typeof DashboardIndexRoute
  '/book/$token/confirmed': typeof BookTokenConfirmedRoute
  '/dashboard/clients/$id': typeof DashboardClientsIdRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/messaging': typeof DashboardSettingsMessagingRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/book/$token': typeof BookTokenIndexRoute
  '/dashboard/clients': typeof DashboardClientsIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/offline': typeof OfflineRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/routes': typeof DashboardRoutesRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/weather': typeof DashboardWeatherRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/book/$token/confirmed': typeof BookTokenConfirmedRoute
  '/dashboard/clients/$id': typeof DashboardClientsIdRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/messaging': typeof DashboardSettingsMessagingRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/book/$token/': typeof BookTokenIndexRoute
  '/dashboard/clients/': typeof DashboardClientsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/offline'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/dashboard/appointments'
    | '/dashboard/chat'
    | '/dashboard/routes'
    | '/dashboard/services'
    | '/dashboard/weather'
    | '/dashboard/'
    | '/book/$token/confirmed'
    | '/dashboard/clients/$id'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/messaging'
    | '/dashboard/settings/profile'
    | '/book/$token/'
    | '/dashboard/clients/'
    | '/dashboard/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/offline'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/dashboard/appointments'
    | '/dashboard/chat'
    | '/dashboard/routes'
    | '/dashboard/services'
    | '/dashboard/weather'
    | '/dashboard'
    | '/book/$token/confirmed'
    | '/dashboard/clients/$id'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/messaging'
    | '/dashboard/settings/profile'
    | '/book/$token'
    | '/dashboard/clients'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/dashboard'
    | '/offline'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_auth/verify-email'
    | '/dashboard/appointments'
    | '/dashboard/chat'
    | '/dashboard/routes'
    | '/dashboard/services'
    | '/dashboard/weather'
    | '/dashboard/'
    | '/book/$token/confirmed'
    | '/dashboard/clients/$id'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/messaging'
    | '/dashboard/settings/profile'
    | '/book/$token/'
    | '/dashboard/clients/'
    | '/dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  OfflineRoute: typeof OfflineRoute
  BookTokenConfirmedRoute: typeof BookTokenConfirmedRoute
  BookTokenIndexRoute: typeof BookTokenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/weather': {
      id: '/dashboard/weather'
      path: '/weather'
      fullPath: '/dashboard/weather'
      preLoaderRoute: typeof DashboardWeatherRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services': {
      id: '/dashboard/services'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/routes': {
      id: '/dashboard/routes'
      path: '/routes'
      fullPath: '/dashboard/routes'
      preLoaderRoute: typeof DashboardRoutesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chat': {
      id: '/dashboard/chat'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardChatRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/appointments': {
      id: '/dashboard/appointments'
      path: '/appointments'
      fullPath: '/dashboard/appointments'
      preLoaderRoute: typeof DashboardAppointmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients/': {
      id: '/dashboard/clients/'
      path: '/clients'
      fullPath: '/dashboard/clients/'
      preLoaderRoute: typeof DashboardClientsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/book/$token/': {
      id: '/book/$token/'
      path: '/book/$token'
      fullPath: '/book/$token/'
      preLoaderRoute: typeof BookTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/profile': {
      id: '/dashboard/settings/profile'
      path: '/settings/profile'
      fullPath: '/dashboard/settings/profile'
      preLoaderRoute: typeof DashboardSettingsProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/messaging': {
      id: '/dashboard/settings/messaging'
      path: '/settings/messaging'
      fullPath: '/dashboard/settings/messaging'
      preLoaderRoute: typeof DashboardSettingsMessagingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/billing': {
      id: '/dashboard/settings/billing'
      path: '/settings/billing'
      fullPath: '/dashboard/settings/billing'
      preLoaderRoute: typeof DashboardSettingsBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients/$id': {
      id: '/dashboard/clients/$id'
      path: '/clients/$id'
      fullPath: '/dashboard/clients/$id'
      preLoaderRoute: typeof DashboardClientsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/book/$token/confirmed': {
      id: '/book/$token/confirmed'
      path: '/book/$token/confirmed'
      fullPath: '/book/$token/confirmed'
      preLoaderRoute: typeof BookTokenConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardAppointmentsRoute: typeof DashboardAppointmentsRoute
  DashboardChatRoute: typeof DashboardChatRoute
  DashboardRoutesRoute: typeof DashboardRoutesRoute
  DashboardServicesRoute: typeof DashboardServicesRoute
  DashboardWeatherRoute: typeof DashboardWeatherRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardClientsIdRoute: typeof DashboardClientsIdRoute
  DashboardSettingsBillingRoute: typeof DashboardSettingsBillingRoute
  DashboardSettingsMessagingRoute: typeof DashboardSettingsMessagingRoute
  DashboardSettingsProfileRoute: typeof DashboardSettingsProfileRoute
  DashboardClientsIndexRoute: typeof DashboardClientsIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAppointmentsRoute: DashboardAppointmentsRoute,
  DashboardChatRoute: DashboardChatRoute,
  DashboardRoutesRoute: DashboardRoutesRoute,
  DashboardServicesRoute: DashboardServicesRoute,
  DashboardWeatherRoute: DashboardWeatherRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardClientsIdRoute: DashboardClientsIdRoute,
  DashboardSettingsBillingRoute: DashboardSettingsBillingRoute,
  DashboardSettingsMessagingRoute: DashboardSettingsMessagingRoute,
  DashboardSettingsProfileRoute: DashboardSettingsProfileRoute,
  DashboardClientsIndexRoute: DashboardClientsIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  OfflineRoute: OfflineRoute,
  BookTokenConfirmedRoute: BookTokenConfirmedRoute,
  BookTokenIndexRoute: BookTokenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
